site_name: Stormwater in District of Columbia
site_url: https://www.stormwaterdc.org/
site_description: Instructions for DOEE's Surface and Groundwater System

extra_css:
  - shared/css/extra.css
extra_javascript:
  - shared/javascript/mathjax.js
  - shared/javascript/externalDOEElinks.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
      name: material
      palette:
            primary: '#248C43' #'#187227'
            accent: 'blue'
      custom_dir: docs/shared/overrides
      features:
      - navigation.instant
#      - navigation.tracking
     # - navigation.sections # Getting rid of this will allow for collapsing under level 2 in nav
      - navigation.indexes # Allows for overview pages at start of sections to be excluded from side bar
#      - toc.integrate # Makes the table of contents integrated into the nav bar (makes page move around too much)
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
#      - navigation.tracking # anchor tracking
      - search.suggest
#      - search.highlight
      - search.share
#      logo: "https://octo.quickbase.com/up/bjezqk3qc/g/rch/eg/va/stars-and-bars.jpg"
      logo: shared/overrides/icons/homepage/DOEE-logo-DC-Flag_Horizontal.png
#      favicon: src-raindrop-notext-favicon.png
      font:
        text: Segoe UI

# Plugins
plugins:
  - search
  - open-in-new-tab

markdown_extensions:
  - toc:
      title: On this Page
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
  - pymdownx.superfences
  - attr_list
  - pymdownx.tasklist: # for custom checkboxes
        custom_checkbox: true
        clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - shared/overrides/.icons

# page tree
nav:
  - Home: index.md
  - Return to the SGS: https://doee.dc.gov/sgs

